export const BASE_CURRENCY = "INR";

// Countries/territories using currencies listed by Cashfree International PG.
// Source: Cashfree docs, "International Payments > IPG > Currencies".
export const CASHFREE_SUPPORTED_COUNTRIES = [
  { code: "AF", name: "Afghanistan", currency: "AFN" },
  { code: "AL", name: "Albania", currency: "ALL" },
  { code: "DZ", name: "Algeria", currency: "DZD" },
  { code: "AS", name: "American Samoa", currency: "USD" },
  { code: "AD", name: "Andorra", currency: "EUR" },
  { code: "AO", name: "Angola", currency: "AOA" },
  { code: "AI", name: "Anguilla", currency: "XCD" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD" },
  { code: "AR", name: "Argentina", currency: "ARS" },
  { code: "AM", name: "Armenia", currency: "AMD" },
  { code: "AW", name: "Aruba", currency: "AWG" },
  { code: "AU", name: "Australia", currency: "AUD" },
  { code: "AT", name: "Austria", currency: "EUR" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN" },
  { code: "BS", name: "Bahamas", currency: "BSD" },
  { code: "BH", name: "Bahrain", currency: "BHD" },
  { code: "BD", name: "Bangladesh", currency: "BDT" },
  { code: "BB", name: "Barbados", currency: "BBD" },
  { code: "BE", name: "Belgium", currency: "EUR" },
  { code: "BZ", name: "Belize", currency: "BZD" },
  { code: "BJ", name: "Benin", currency: "XOF" },
  { code: "BM", name: "Bermuda", currency: "BMD" },
  { code: "BT", name: "Bhutan", currency: "BTN" },
  { code: "BO", name: "Bolivia", currency: "BOB" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM" },
  { code: "BW", name: "Botswana", currency: "BWP" },
  { code: "BR", name: "Brazil", currency: "BRL" },
  { code: "VG", name: "British Virgin Islands", currency: "USD" },
  { code: "BN", name: "Brunei", currency: "BND" },
  { code: "BG", name: "Bulgaria", currency: "BGN" },
  { code: "BF", name: "Burkina Faso", currency: "XOF" },
  { code: "BI", name: "Burundi", currency: "BIF" },
  { code: "KH", name: "Cambodia", currency: "KHR" },
  { code: "CM", name: "Cameroon", currency: "XAF" },
  { code: "CA", name: "Canada", currency: "CAD" },
  { code: "CV", name: "Cape Verde", currency: "CVE" },
  { code: "KY", name: "Cayman Islands", currency: "KYD" },
  { code: "CF", name: "Central African Republic", currency: "XAF" },
  { code: "TD", name: "Chad", currency: "XAF" },
  { code: "CL", name: "Chile", currency: "CLP" },
  { code: "CN", name: "China", currency: "CNY" },
  { code: "CO", name: "Colombia", currency: "COP" },
  { code: "KM", name: "Comoros", currency: "KMF" },
  { code: "CG", name: "Congo (Brazzaville)", currency: "XAF" },
  { code: "CD", name: "Congo (Kinshasa)", currency: "CDF" },
  { code: "CK", name: "Cook Islands", currency: "NZD" },
  { code: "CR", name: "Costa Rica", currency: "CRC" },
  { code: "CI", name: "Cote d'Ivoire", currency: "XOF" },
  { code: "HR", name: "Croatia", currency: "EUR" },
  { code: "CY", name: "Cyprus", currency: "EUR" },
  { code: "CZ", name: "Czechia", currency: "CZK" },
  { code: "DK", name: "Denmark", currency: "DKK" },
  { code: "DJ", name: "Djibouti", currency: "DJF" },
  { code: "DM", name: "Dominica", currency: "XCD" },
  { code: "DO", name: "Dominican Republic", currency: "DOP" },
  { code: "EC", name: "Ecuador", currency: "USD" },
  { code: "EG", name: "Egypt", currency: "EGP" },
  { code: "SV", name: "El Salvador", currency: "USD" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF" },
  { code: "ER", name: "Eritrea", currency: "ERN" },
  { code: "EE", name: "Estonia", currency: "EUR" },
  { code: "SZ", name: "Eswatini", currency: "SZL" },
  { code: "ET", name: "Ethiopia", currency: "ETB" },
  { code: "FK", name: "Falkland Islands", currency: "FKP" },
  { code: "FO", name: "Faroe Islands", currency: "DKK" },
  { code: "FJ", name: "Fiji", currency: "FJD" },
  { code: "FI", name: "Finland", currency: "EUR" },
  { code: "FR", name: "France", currency: "EUR" },
  { code: "GF", name: "French Guiana", currency: "EUR" },
  { code: "PF", name: "French Polynesia", currency: "XPF" },
  { code: "GA", name: "Gabon", currency: "XAF" },
  { code: "GM", name: "Gambia", currency: "GMD" },
  { code: "GE", name: "Georgia", currency: "GEL" },
  { code: "DE", name: "Germany", currency: "EUR" },
  { code: "GH", name: "Ghana", currency: "GHS" },
  { code: "GI", name: "Gibraltar", currency: "GIP" },
  { code: "GR", name: "Greece", currency: "EUR" },
  { code: "GL", name: "Greenland", currency: "DKK" },
  { code: "GD", name: "Grenada", currency: "XCD" },
  { code: "GP", name: "Guadeloupe", currency: "EUR" },
  { code: "GU", name: "Guam", currency: "USD" },
  { code: "GT", name: "Guatemala", currency: "GTQ" },
  { code: "GG", name: "Guernsey", currency: "GBP" },
  { code: "GN", name: "Guinea", currency: "GNF" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF" },
  { code: "GY", name: "Guyana", currency: "GYD" },
  { code: "HT", name: "Haiti", currency: "HTG" },
  { code: "HN", name: "Honduras", currency: "HNL" },
  { code: "HK", name: "Hong Kong", currency: "HKD" },
  { code: "HU", name: "Hungary", currency: "HUF" },
  { code: "IS", name: "Iceland", currency: "ISK" },
  { code: "IN", name: "India", currency: "INR" },
  { code: "ID", name: "Indonesia", currency: "IDR" },
  { code: "IQ", name: "Iraq", currency: "IQD" },
  { code: "IE", name: "Ireland", currency: "EUR" },
  { code: "IM", name: "Isle of Man", currency: "GBP" },
  { code: "IL", name: "Israel", currency: "ILS" },
  { code: "IT", name: "Italy", currency: "EUR" },
  { code: "JM", name: "Jamaica", currency: "JMD" },
  { code: "JP", name: "Japan", currency: "JPY" },
  { code: "JE", name: "Jersey", currency: "GBP" },
  { code: "JO", name: "Jordan", currency: "JOD" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT" },
  { code: "KE", name: "Kenya", currency: "KES" },
  { code: "KI", name: "Kiribati", currency: "AUD" },
  { code: "XK", name: "Kosovo", currency: "EUR" },
  { code: "KW", name: "Kuwait", currency: "KWD" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS" },
  { code: "LA", name: "Laos", currency: "LAK" },
  { code: "LV", name: "Latvia", currency: "EUR" },
  { code: "LB", name: "Lebanon", currency: "LBP" },
  { code: "LR", name: "Liberia", currency: "LRD" },
  { code: "LY", name: "Libya", currency: "LYD" },
  { code: "LI", name: "Liechtenstein", currency: "CHF" },
  { code: "LT", name: "Lithuania", currency: "EUR" },
  { code: "LU", name: "Luxembourg", currency: "EUR" },
  { code: "MO", name: "Macau", currency: "MOP" },
  { code: "MG", name: "Madagascar", currency: "MGA" },
  { code: "MW", name: "Malawi", currency: "MWK" },
  { code: "MY", name: "Malaysia", currency: "MYR" },
  { code: "MV", name: "Maldives", currency: "MVR" },
  { code: "ML", name: "Mali", currency: "XOF" },
  { code: "MT", name: "Malta", currency: "EUR" },
  { code: "MH", name: "Marshall Islands", currency: "USD" },
  { code: "MQ", name: "Martinique", currency: "EUR" },
  { code: "MR", name: "Mauritania", currency: "MRU" },
  { code: "MU", name: "Mauritius", currency: "MUR" },
  { code: "YT", name: "Mayotte", currency: "EUR" },
  { code: "MX", name: "Mexico", currency: "MXN" },
  { code: "FM", name: "Micronesia", currency: "USD" },
  { code: "MD", name: "Moldova", currency: "MDL" },
  { code: "MC", name: "Monaco", currency: "EUR" },
  { code: "MN", name: "Mongolia", currency: "MNT" },
  { code: "ME", name: "Montenegro", currency: "EUR" },
  { code: "MS", name: "Montserrat", currency: "XCD" },
  { code: "MA", name: "Morocco", currency: "MAD" },
  { code: "MZ", name: "Mozambique", currency: "MZN" },
  { code: "NA", name: "Namibia", currency: "NAD" },
  { code: "NR", name: "Nauru", currency: "AUD" },
  { code: "NP", name: "Nepal", currency: "NPR" },
  { code: "NL", name: "Netherlands", currency: "EUR" },
  { code: "NC", name: "New Caledonia", currency: "XPF" },
  { code: "NZ", name: "New Zealand", currency: "NZD" },
  { code: "NI", name: "Nicaragua", currency: "NIO" },
  { code: "NE", name: "Niger", currency: "XOF" },
  { code: "NG", name: "Nigeria", currency: "NGN" },
  { code: "NU", name: "Niue", currency: "NZD" },
  { code: "MK", name: "North Macedonia", currency: "MKD" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD" },
  { code: "NO", name: "Norway", currency: "NOK" },
  { code: "OM", name: "Oman", currency: "OMR" },
  { code: "PW", name: "Palau", currency: "USD" },
  { code: "PA", name: "Panama", currency: "USD" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK" },
  { code: "PY", name: "Paraguay", currency: "PYG" },
  { code: "PE", name: "Peru", currency: "PEN" },
  { code: "PH", name: "Philippines", currency: "PHP" },
  { code: "PL", name: "Poland", currency: "PLN" },
  { code: "PT", name: "Portugal", currency: "EUR" },
  { code: "PR", name: "Puerto Rico", currency: "USD" },
  { code: "QA", name: "Qatar", currency: "QAR" },
  { code: "RE", name: "Reunion", currency: "EUR" },
  { code: "RO", name: "Romania", currency: "RON" },
  { code: "RU", name: "Russia", currency: "RUB" },
  { code: "RW", name: "Rwanda", currency: "RWF" },
  { code: "BL", name: "Saint Barthelemy", currency: "EUR" },
  { code: "SH", name: "Saint Helena", currency: "SHP" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD" },
  { code: "LC", name: "Saint Lucia", currency: "XCD" },
  { code: "MF", name: "Saint Martin", currency: "EUR" },
  { code: "PM", name: "Saint Pierre and Miquelon", currency: "EUR" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD" },
  { code: "WS", name: "Samoa", currency: "WST" },
  { code: "SM", name: "San Marino", currency: "EUR" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR" },
  { code: "SN", name: "Senegal", currency: "XOF" },
  { code: "RS", name: "Serbia", currency: "RSD" },
  { code: "SC", name: "Seychelles", currency: "SCR" },
  { code: "SL", name: "Sierra Leone", currency: "SLL" },
  { code: "SG", name: "Singapore", currency: "SGD" },
  { code: "SK", name: "Slovakia", currency: "EUR" },
  { code: "SI", name: "Slovenia", currency: "EUR" },
  { code: "SB", name: "Solomon Islands", currency: "SBD" },
  { code: "SO", name: "Somalia", currency: "SOS" },
  { code: "ZA", name: "South Africa", currency: "ZAR" },
  { code: "KR", name: "South Korea", currency: "KRW" },
  { code: "ES", name: "Spain", currency: "EUR" },
  { code: "LK", name: "Sri Lanka", currency: "LKR" },
  { code: "SR", name: "Suriname", currency: "SRD" },
  { code: "SE", name: "Sweden", currency: "SEK" },
  { code: "CH", name: "Switzerland", currency: "CHF" },
  { code: "TW", name: "Taiwan", currency: "TWD" },
  { code: "TJ", name: "Tajikistan", currency: "TJS" },
  { code: "TZ", name: "Tanzania", currency: "TZS" },
  { code: "TH", name: "Thailand", currency: "THB" },
  { code: "TL", name: "Timor-Leste", currency: "USD" },
  { code: "TG", name: "Togo", currency: "XOF" },
  { code: "TO", name: "Tonga", currency: "TOP" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD" },
  { code: "TN", name: "Tunisia", currency: "TND" },
  { code: "TR", name: "Turkey", currency: "TRY" },
  { code: "TM", name: "Turkmenistan", currency: "TMT" },
  { code: "TC", name: "Turks and Caicos Islands", currency: "USD" },
  { code: "TV", name: "Tuvalu", currency: "AUD" },
  { code: "AE", name: "United Arab Emirates", currency: "AED" },
  { code: "UG", name: "Uganda", currency: "UGX" },
  { code: "UA", name: "Ukraine", currency: "UAH" },
  { code: "GB", name: "United Kingdom", currency: "GBP" },
  { code: "US", name: "United States", currency: "USD" },
  { code: "UY", name: "Uruguay", currency: "UYU" },
  { code: "VI", name: "US Virgin Islands", currency: "USD" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS" },
  { code: "VU", name: "Vanuatu", currency: "VUV" },
  { code: "VA", name: "Vatican City", currency: "EUR" },
  { code: "VN", name: "Vietnam", currency: "VND" },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF" },
  { code: "YE", name: "Yemen", currency: "YER" },
  { code: "ZM", name: "Zambia", currency: "ZMW" },
];

export const CASHFREE_SUPPORTED_CURRENCIES = [
  ...new Set(CASHFREE_SUPPORTED_COUNTRIES.map((country) => country.currency)),
].sort();

const CURRENCY_BY_COUNTRY = CASHFREE_SUPPORTED_COUNTRIES.reduce(
  (acc, country) => {
    acc[country.code] = country.currency;
    return acc;
  },
  {},
);

const COUNTRY_ALIASES = {
  AMERICA: "US",
  AUSTRALIA: "AU",
  BHARAT: "IN",
  BRITAIN: "GB",
  CANADA: "CA",
  COTEDIVOIRE: "CI",
  CZECHREPUBLIC: "CZ",
  DEMOCRATICREPUBLICOFCONGO: "CD",
  DRCONGO: "CD",
  ENGLAND: "GB",
  INDIA: "IN",
  JAPAN: "JP",
  NEWZEALAND: "NZ",
  REPUBLICOFCONGO: "CG",
  SINGAPORE: "SG",
  SOUTHAFRICA: "ZA",
  SOUTHKOREA: "KR",
  TAIWAN: "TW",
  UK: "GB",
  UAE: "AE",
  UNITEDARABEMIRATES: "AE",
  UNITEDKINGDOM: "GB",
  UNITEDSTATES: "US",
  UNITEDSTATESOFAMERICA: "US",
  USA: "US",
};

// Static approximate rates from INR. Replace with a server-fed rate table when needed.
export const INR_FX_RATES = {
  INR: 1,
  AED: 0.044,
  AFN: 0.84,
  ALL: 1.05,
  AMD: 4.6,
  AOA: 10.5,
  ARS: 14,
  AUD: 0.018,
  AWG: 0.022,
  AZN: 0.02,
  BAM: 0.021,
  BBD: 0.024,
  BDT: 1.45,
  BGN: 0.021,
  BHD: 0.0045,
  BIF: 35,
  BMD: 0.012,
  BND: 0.016,
  BOB: 0.083,
  BRL: 0.066,
  BSD: 0.012,
  BTN: 1,
  BWP: 0.16,
  BZD: 0.024,
  CAD: 0.017,
  CDF: 34,
  CHF: 0.01,
  CLP: 11,
  CNY: 0.086,
  COP: 48,
  CRC: 6,
  CVE: 1.2,
  CZK: 0.27,
  DJF: 2.13,
  DKK: 0.08,
  DOP: 0.72,
  DZD: 1.55,
  EGP: 0.57,
  ERN: 0.18,
  ETB: 1.6,
  EUR: 0.011,
  FJD: 0.027,
  FKP: 0.0095,
  GBP: 0.0095,
  GEL: 0.033,
  GHS: 0.13,
  GIP: 0.0095,
  GMD: 0.86,
  GNF: 103,
  GTQ: 0.092,
  GYD: 2.5,
  HKD: 0.093,
  HNL: 0.31,
  HTG: 1.57,
  HUF: 4.2,
  IDR: 195,
  ILS: 0.04,
  IQD: 15.7,
  ISK: 1.5,
  JMD: 1.9,
  JOD: 0.0085,
  JPY: 1.8,
  KES: 1.55,
  KGS: 1.05,
  KHR: 49,
  KMF: 5.4,
  KRW: 16.5,
  KWD: 0.0037,
  KYD: 0.01,
  KZT: 6.2,
  LAK: 260,
  LBP: 1075,
  LKR: 3.6,
  LRD: 2.4,
  LYD: 0.065,
  MAD: 0.11,
  MDL: 0.21,
  MGA: 54,
  MKD: 0.66,
  MNT: 42,
  MOP: 0.096,
  MRU: 0.48,
  MUR: 0.55,
  MVR: 0.185,
  MWK: 20.8,
  MXN: 0.22,
  MYR: 0.052,
  MZN: 0.77,
  NAD: 0.21,
  NGN: 18,
  NIO: 0.44,
  NOK: 0.12,
  NPR: 1.6,
  NZD: 0.02,
  OMR: 0.0046,
  PEN: 0.043,
  PGK: 0.049,
  PHP: 0.68,
  PLN: 0.041,
  PYG: 90,
  QAR: 0.044,
  RON: 0.054,
  RSD: 1.25,
  RUB: 0.95,
  RWF: 17,
  SAR: 0.045,
  SBD: 0.1,
  SCR: 0.18,
  SEK: 0.12,
  SGD: 0.016,
  SHP: 0.0095,
  SLL: 250,
  SOS: 6.8,
  SRD: 0.45,
  SZL: 0.21,
  THB: 0.39,
  TJS: 0.13,
  TMT: 0.042,
  TND: 0.036,
  TOP: 0.028,
  TRY: 0.39,
  TTD: 0.081,
  TWD: 0.36,
  TZS: 30,
  UAH: 0.5,
  UGX: 43,
  USD: 0.012,
  UYU: 0.48,
  UZS: 150,
  VND: 300,
  VUV: 1.4,
  WST: 0.033,
  XAF: 7.1,
  XCD: 0.032,
  XOF: 7.1,
  XPF: 1.3,
  YER: 3,
  ZAR: 0.21,
  ZMW: 0.28,
};

export const CURRENCY_SYMBOLS = {
  INR: "₹",
  AED: "د.إ",
  AUD: "A$",
  CAD: "C$",
  CHF: "CHF",
  CNY: "¥",
  EUR: "€",
  GBP: "£",
  HKD: "HK$",
  JPY: "¥",
  KRW: "₩",
  NZD: "NZ$",
  SGD: "S$",
  USD: "$",
  ZAR: "R",
};

let userCountry = "";

function normalizeCountryKey(value) {
  return String(value || "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "");
}

const COUNTRY_LOOKUP = CASHFREE_SUPPORTED_COUNTRIES.reduce((acc, country) => {
  acc[normalizeCountryKey(country.code)] = country;
  acc[normalizeCountryKey(country.name)] = country;
  return acc;
}, {});

function countryCodeFromInput(country) {
  const key = normalizeCountryKey(country);
  if (!key) return "";
  if (CURRENCY_BY_COUNTRY[key]) return key;
  if (COUNTRY_ALIASES[key]) return COUNTRY_ALIASES[key];
  return COUNTRY_LOOKUP[key]?.code || "";
}

export function getSupportedCountryOption(country) {
  const region = countryCodeFromInput(country);
  return region ? COUNTRY_LOOKUP[region] || null : null;
}

export function setUserCurrencyCountry(country) {
  userCountry = String(country || "").trim();
}

export function getCurrencyInfoForCountry(country) {
  const selectedCountry = getSupportedCountryOption(country);
  const region = selectedCountry?.code || countryCodeFromInput(country);
  const currency = selectedCountry?.currency || CURRENCY_BY_COUNTRY[region] || BASE_CURRENCY;
  return {
    currency,
    country: selectedCountry?.name || String(country || "").trim(),
    region: region || "IN",
    symbol: CURRENCY_SYMBOLS[currency] || currency,
    rateFromInr: INR_FX_RATES[currency] || 1,
  };
}

export function getUserCurrencyInfo(countryOverride = null) {
  return getCurrencyInfoForCountry(countryOverride ?? userCountry);
}

export function convertInrToCurrency(amountInr, currencyInfo = getUserCurrencyInfo()) {
  const amount = Number(amountInr) || 0;
  const rate = Number(currencyInfo?.rateFromInr) || 1;
  return Math.max(0, Math.round(amount * rate));
}

export function formatCurrencyFromInr(amountInr, currencyInfo = getUserCurrencyInfo()) {
  const currency = currencyInfo?.currency || BASE_CURRENCY;
  const symbol = currencyInfo?.symbol || CURRENCY_SYMBOLS[currency] || currency;
  const converted = convertInrToCurrency(amountInr, currencyInfo);
  const formatted = converted.toLocaleString();
  return symbol === currency ? `${currency} ${formatted}` : `${symbol}${formatted}`;
}

export function cashfreeAmountForInr(amountInr, currencyInfo = getUserCurrencyInfo()) {
  const currency = currencyInfo?.currency || BASE_CURRENCY;
  const amount = convertInrToCurrency(amountInr, currencyInfo);
  return {
    currency,
    amount,
    amountMinor: Math.max(100, Math.round(amount * 100)),
    baseCurrency: BASE_CURRENCY,
    baseAmountInr: Math.max(0, Math.round(Number(amountInr) || 0)),
    fxRateFromInr: Number(currencyInfo?.rateFromInr) || 1,
    approximate: currency !== BASE_CURRENCY,
  };
}
